# Generated by Django 3.1.2 on 2020-10-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sintomas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('dolorGarganta', models.IntegerField()),
                ('tos', models.IntegerField()),
                ('senGusto', models.IntegerField()),
                ('senOlfato', models.IntegerField()),
                ('respiracion', models.IntegerField()),
            ],
        ),
    ]
