# Generated by Django 3.1.2 on 2020-10-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomaDatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sintomas',
            name='dolorPecho',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='senGusto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='senOlfato',
            field=models.TextField(),
        ),
    ]
