# Generated by Django 3.1.2 on 2020-11-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomaDatos', '0002_auto_20201031_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='sintomas',
            name='Diarrea',
            field=models.TextField(default='No'),
        ),
        migrations.AddField(
            model_name='sintomas',
            name='DolorCabeza',
            field=models.TextField(default='No'),
        ),
        migrations.AddField(
            model_name='sintomas',
            name='DolorEspalda',
            field=models.TextField(default='No'),
        ),
        migrations.AddField(
            model_name='sintomas',
            name='Malestar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sintomas',
            name='Secrecion',
            field=models.TextField(default='No'),
        ),
    ]
