# Generated by Django 3.1.2 on 2020-11-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomaDatos', '0003_auto_20201117_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='sintomas',
            name='resultado',
            field=models.TextField(default='No', null=True),
        ),
    ]
